blank_issues_enabled: false
contact_links:
  - name: Azahar Discord
    url: https://discord.com/invite/4ZjMpAp3M6
    about: If you are experiencing an issue and you need support, or if you have a general question, try asking in the official Discord linked here. *Discussion of piracy is not allowed.*
